set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(LLVM_CLANG_TARGET_TRIPLE "aarch64-apple-macos15.0.0")
set(CMAKE_SYSROOT "C:/SDKs/MacOSX15.5.sdk")

set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET ${LLVM_CLANG_TARGET_TRIPLE})
set(CMAKE_C_FLAGS_INIT)

set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET ${LLVM_CLANG_TARGET_TRIPLE})
set(CMAKE_CXX_FLAGS_INIT)

set(CMAKE_EXE_LINKER_FLAGS    "-fuse-ld=lld")
set(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_AR "llvm-ar")