set(CMAKE_SYSTEM_NAME Darwin)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(LLVM_CLANG_TARGET_TRIPLE "aarch64-apple-darwin")

set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET ${LLVM_CLANG_TARGET_TRIPLE})