# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "3.0.0")
   message(FATAL_ERROR "CMake >= 3.0.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 3.0.0...4.0)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS UnitsEngine::UnitsEngine UnitsEngine::spdlog_header_only UnitsEngine::ImGui UnitsEngine::glm-header-only UnitsEngine::SDL3-static UnitsEngine::Headers)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# The installation prefix configured by this project.
set(_IMPORT_PREFIX "C:/Users/Jesse/Desktop/Github/UnitsEngine/install/UnitsEngine-v1.1")

# Create imported target UnitsEngine::UnitsEngine
add_library(UnitsEngine::UnitsEngine SHARED IMPORTED)

set_target_properties(UnitsEngine::UnitsEngine PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<CONFIG:Debug>:UE_DEBUG>;\$<\$<CONFIG:Debug>:UE_ASSERT_ENABLED>;\$<\$<CONFIG:Debug>:UE_LOGGING_ENABLED>"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Jesse/Desktop/Github/UnitsEngine/install/UnitsEngine-v1.1/include;C:/Users/Jesse/Desktop/Github/UnitsEngine/install/UnitsEngine-v1.1/include"
  INTERFACE_LINK_LIBRARIES "UnitsEngine::spdlog_header_only;UnitsEngine::ImGui;UnitsEngine::glm-header-only"
)

# Create imported target UnitsEngine::spdlog_header_only
add_library(UnitsEngine::spdlog_header_only INTERFACE IMPORTED)

set_target_properties(UnitsEngine::spdlog_header_only PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "SPDLOG_FWRITE_UNLOCKED"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;C:/Users/Jesse/Desktop/Github/UnitsEngine/install/UnitsEngine-v1.1/include"
  INTERFACE_LINK_LIBRARIES "Threads::Threads"
)

# Create imported target UnitsEngine::ImGui
add_library(UnitsEngine::ImGui STATIC IMPORTED)

set_target_properties(UnitsEngine::ImGui PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Jesse/Desktop/Github/UnitsEngine/install/UnitsEngine-v1.1/include/imgui;C:/Users/Jesse/Desktop/Github/UnitsEngine/install/UnitsEngine-v1.1/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:UnitsEngine::SDL3-static>"
)

# Create imported target UnitsEngine::glm-header-only
add_library(UnitsEngine::glm-header-only INTERFACE IMPORTED)

set_target_properties(UnitsEngine::glm-header-only PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;C:/Users/Jesse/Desktop/Github/UnitsEngine/install/UnitsEngine-v1.1/include"
)

# Create imported target UnitsEngine::SDL3-static
add_library(UnitsEngine::SDL3-static STATIC IMPORTED)

set_target_properties(UnitsEngine::SDL3-static PROPERTIES
  COMPATIBLE_INTERFACE_BOOL "SDL3_SHARED"
  COMPATIBLE_INTERFACE_STRING "SDL_VERSION"
  INTERFACE_INCLUDE_DIRECTORIES "C:/Users/Jesse/Desktop/Github/UnitsEngine/install/UnitsEngine-v1.1/include"
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:m>;\$<LINK_ONLY:kernel32>;\$<LINK_ONLY:user32>;\$<LINK_ONLY:gdi32>;\$<LINK_ONLY:winmm>;\$<LINK_ONLY:imm32>;\$<LINK_ONLY:ole32>;\$<LINK_ONLY:oleaut32>;\$<LINK_ONLY:version>;\$<LINK_ONLY:uuid>;\$<LINK_ONLY:advapi32>;\$<LINK_ONLY:setupapi>;\$<LINK_ONLY:shell32>;\$<LINK_ONLY:dinput8>;UnitsEngine::Headers"
  INTERFACE_SDL3_SHARED "FALSE"
  INTERFACE_SDL_VERSION "SDL3"
)

# Create imported target UnitsEngine::Headers
add_library(UnitsEngine::Headers INTERFACE IMPORTED)

set_target_properties(UnitsEngine::Headers PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;C:/Users/Jesse/Desktop/Github/UnitsEngine/install/UnitsEngine-v1.1/include"
)

# Load information for each installed configuration.
file(GLOB _cmake_config_files "${CMAKE_CURRENT_LIST_DIR}/UnitsEngine_export-*.cmake")
foreach(_cmake_config_file IN LISTS _cmake_config_files)
  include("${_cmake_config_file}")
endforeach()
unset(_cmake_config_file)
unset(_cmake_config_files)

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(_cmake_target IN LISTS _cmake_import_check_targets)
  if(CMAKE_VERSION VERSION_LESS "3.28"
      OR NOT DEFINED _cmake_import_check_xcframework_for_${_cmake_target}
      OR NOT IS_DIRECTORY "${_cmake_import_check_xcframework_for_${_cmake_target}}")
    foreach(_cmake_file IN LISTS "_cmake_import_check_files_for_${_cmake_target}")
      if(NOT EXISTS "${_cmake_file}")
        message(FATAL_ERROR "The imported target \"${_cmake_target}\" references the file
   \"${_cmake_file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
      endif()
    endforeach()
  endif()
  unset(_cmake_file)
  unset("_cmake_import_check_files_for_${_cmake_target}")
endforeach()
unset(_cmake_target)
unset(_cmake_import_check_targets)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
